# Generated by Django 2.1.1 on 2018-09-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderedQuantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.IntegerField()),
                ('orderAmount', models.FloatField()),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField()),
                ('productName', models.CharField(max_length=250)),
                ('productDescription', models.CharField(max_length=500)),
                ('productPrize', models.FloatField()),
                ('productQuantity', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeID', models.IntegerField()),
                ('storeName', models.CharField(max_length=250)),
                ('storeDescription', models.CharField(max_length=500)),
                ('storeAddress', models.CharField(max_length=500)),
                ('storeCatagory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('userName', models.CharField(max_length=100)),
                ('userAddress', models.CharField(max_length=500)),
                ('userPhone', models.IntegerField(max_length=20)),
                ('userPinCode', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Stores'),
        ),
        migrations.AddField(
            model_name='orderslist',
            name='storeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App1.Stores'),
        ),
        migrations.AddField(
            model_name='orderslist',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Users'),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='orderDataID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.OrdersList'),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='orderedProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App1.Products'),
        ),
    ]
