# Generated by Django 2.1.1 on 2018-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userPhone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='userPinCode',
            field=models.IntegerField(),
        ),
    ]
